# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/alexander_serov/Google Drive/Work/07_France (2012-2015)/05_Image segmentation project/11_Terminal project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/alexander_serov/Google Drive/Work/07_France (2012-2015)/05_Image segmentation project/11_Terminal project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexander_serov/Google Drive/Work/07_France (2012-2015)/05_Image segmentation project/11_Terminal project/CMakeFiles" "/Users/alexander_serov/Google Drive/Work/07_France (2012-2015)/05_Image segmentation project/11_Terminal project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/alexander_serov/Google Drive/Work/07_France (2012-2015)/05_Image segmentation project/11_Terminal project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Human_placenta

# Build rule for target.
Human_placenta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Human_placenta
.PHONY : Human_placenta

# fast build rule for target.
Human_placenta/fast:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/build
.PHONY : Human_placenta/fast

core/algorithm/GeometricalTransformation.o: core/algorithm/GeometricalTransformation.cpp.o

.PHONY : core/algorithm/GeometricalTransformation.o

# target to build an object file
core/algorithm/GeometricalTransformation.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/GeometricalTransformation.cpp.o
.PHONY : core/algorithm/GeometricalTransformation.cpp.o

core/algorithm/GeometricalTransformation.i: core/algorithm/GeometricalTransformation.cpp.i

.PHONY : core/algorithm/GeometricalTransformation.i

# target to preprocess a source file
core/algorithm/GeometricalTransformation.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/GeometricalTransformation.cpp.i
.PHONY : core/algorithm/GeometricalTransformation.cpp.i

core/algorithm/GeometricalTransformation.s: core/algorithm/GeometricalTransformation.cpp.s

.PHONY : core/algorithm/GeometricalTransformation.s

# target to generate assembly for a file
core/algorithm/GeometricalTransformation.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/GeometricalTransformation.cpp.s
.PHONY : core/algorithm/GeometricalTransformation.cpp.s

core/algorithm/LinearAlgebra.o: core/algorithm/LinearAlgebra.cpp.o

.PHONY : core/algorithm/LinearAlgebra.o

# target to build an object file
core/algorithm/LinearAlgebra.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/LinearAlgebra.cpp.o
.PHONY : core/algorithm/LinearAlgebra.cpp.o

core/algorithm/LinearAlgebra.i: core/algorithm/LinearAlgebra.cpp.i

.PHONY : core/algorithm/LinearAlgebra.i

# target to preprocess a source file
core/algorithm/LinearAlgebra.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/LinearAlgebra.cpp.i
.PHONY : core/algorithm/LinearAlgebra.cpp.i

core/algorithm/LinearAlgebra.s: core/algorithm/LinearAlgebra.cpp.s

.PHONY : core/algorithm/LinearAlgebra.s

# target to generate assembly for a file
core/algorithm/LinearAlgebra.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/LinearAlgebra.cpp.s
.PHONY : core/algorithm/LinearAlgebra.cpp.s

core/algorithm/RandomGeometry.o: core/algorithm/RandomGeometry.cpp.o

.PHONY : core/algorithm/RandomGeometry.o

# target to build an object file
core/algorithm/RandomGeometry.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/RandomGeometry.cpp.o
.PHONY : core/algorithm/RandomGeometry.cpp.o

core/algorithm/RandomGeometry.i: core/algorithm/RandomGeometry.cpp.i

.PHONY : core/algorithm/RandomGeometry.i

# target to preprocess a source file
core/algorithm/RandomGeometry.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/RandomGeometry.cpp.i
.PHONY : core/algorithm/RandomGeometry.cpp.i

core/algorithm/RandomGeometry.s: core/algorithm/RandomGeometry.cpp.s

.PHONY : core/algorithm/RandomGeometry.s

# target to generate assembly for a file
core/algorithm/RandomGeometry.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/RandomGeometry.cpp.s
.PHONY : core/algorithm/RandomGeometry.cpp.s

core/algorithm/Statistics.o: core/algorithm/Statistics.cpp.o

.PHONY : core/algorithm/Statistics.o

# target to build an object file
core/algorithm/Statistics.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/Statistics.cpp.o
.PHONY : core/algorithm/Statistics.cpp.o

core/algorithm/Statistics.i: core/algorithm/Statistics.cpp.i

.PHONY : core/algorithm/Statistics.i

# target to preprocess a source file
core/algorithm/Statistics.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/Statistics.cpp.i
.PHONY : core/algorithm/Statistics.cpp.i

core/algorithm/Statistics.s: core/algorithm/Statistics.cpp.s

.PHONY : core/algorithm/Statistics.s

# target to generate assembly for a file
core/algorithm/Statistics.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/Statistics.cpp.s
.PHONY : core/algorithm/Statistics.cpp.s

core/algorithm/Visualization.o: core/algorithm/Visualization.cpp.o

.PHONY : core/algorithm/Visualization.o

# target to build an object file
core/algorithm/Visualization.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/Visualization.cpp.o
.PHONY : core/algorithm/Visualization.cpp.o

core/algorithm/Visualization.i: core/algorithm/Visualization.cpp.i

.PHONY : core/algorithm/Visualization.i

# target to preprocess a source file
core/algorithm/Visualization.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/Visualization.cpp.i
.PHONY : core/algorithm/Visualization.cpp.i

core/algorithm/Visualization.s: core/algorithm/Visualization.cpp.s

.PHONY : core/algorithm/Visualization.s

# target to generate assembly for a file
core/algorithm/Visualization.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/algorithm/Visualization.cpp.s
.PHONY : core/algorithm/Visualization.cpp.s

core/data/3d/GLFigure.o: core/data/3d/GLFigure.cpp.o

.PHONY : core/data/3d/GLFigure.o

# target to build an object file
core/data/3d/GLFigure.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/3d/GLFigure.cpp.o
.PHONY : core/data/3d/GLFigure.cpp.o

core/data/3d/GLFigure.i: core/data/3d/GLFigure.cpp.i

.PHONY : core/data/3d/GLFigure.i

# target to preprocess a source file
core/data/3d/GLFigure.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/3d/GLFigure.cpp.i
.PHONY : core/data/3d/GLFigure.cpp.i

core/data/3d/GLFigure.s: core/data/3d/GLFigure.cpp.s

.PHONY : core/data/3d/GLFigure.s

# target to generate assembly for a file
core/data/3d/GLFigure.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/3d/GLFigure.cpp.s
.PHONY : core/data/3d/GLFigure.cpp.s

core/data/distribution/Distribution.o: core/data/distribution/Distribution.cpp.o

.PHONY : core/data/distribution/Distribution.o

# target to build an object file
core/data/distribution/Distribution.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/Distribution.cpp.o
.PHONY : core/data/distribution/Distribution.cpp.o

core/data/distribution/Distribution.i: core/data/distribution/Distribution.cpp.i

.PHONY : core/data/distribution/Distribution.i

# target to preprocess a source file
core/data/distribution/Distribution.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/Distribution.cpp.i
.PHONY : core/data/distribution/Distribution.cpp.i

core/data/distribution/Distribution.s: core/data/distribution/Distribution.cpp.s

.PHONY : core/data/distribution/Distribution.s

# target to generate assembly for a file
core/data/distribution/Distribution.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/Distribution.cpp.s
.PHONY : core/data/distribution/Distribution.cpp.s

core/data/distribution/DistributionAnalytic.o: core/data/distribution/DistributionAnalytic.cpp.o

.PHONY : core/data/distribution/DistributionAnalytic.o

# target to build an object file
core/data/distribution/DistributionAnalytic.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionAnalytic.cpp.o
.PHONY : core/data/distribution/DistributionAnalytic.cpp.o

core/data/distribution/DistributionAnalytic.i: core/data/distribution/DistributionAnalytic.cpp.i

.PHONY : core/data/distribution/DistributionAnalytic.i

# target to preprocess a source file
core/data/distribution/DistributionAnalytic.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionAnalytic.cpp.i
.PHONY : core/data/distribution/DistributionAnalytic.cpp.i

core/data/distribution/DistributionAnalytic.s: core/data/distribution/DistributionAnalytic.cpp.s

.PHONY : core/data/distribution/DistributionAnalytic.s

# target to generate assembly for a file
core/data/distribution/DistributionAnalytic.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionAnalytic.cpp.s
.PHONY : core/data/distribution/DistributionAnalytic.cpp.s

core/data/distribution/DistributionArithmetic.o: core/data/distribution/DistributionArithmetic.cpp.o

.PHONY : core/data/distribution/DistributionArithmetic.o

# target to build an object file
core/data/distribution/DistributionArithmetic.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionArithmetic.cpp.o
.PHONY : core/data/distribution/DistributionArithmetic.cpp.o

core/data/distribution/DistributionArithmetic.i: core/data/distribution/DistributionArithmetic.cpp.i

.PHONY : core/data/distribution/DistributionArithmetic.i

# target to preprocess a source file
core/data/distribution/DistributionArithmetic.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionArithmetic.cpp.i
.PHONY : core/data/distribution/DistributionArithmetic.cpp.i

core/data/distribution/DistributionArithmetic.s: core/data/distribution/DistributionArithmetic.cpp.s

.PHONY : core/data/distribution/DistributionArithmetic.s

# target to generate assembly for a file
core/data/distribution/DistributionArithmetic.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionArithmetic.cpp.s
.PHONY : core/data/distribution/DistributionArithmetic.cpp.s

core/data/distribution/DistributionFromDataStructure.o: core/data/distribution/DistributionFromDataStructure.cpp.o

.PHONY : core/data/distribution/DistributionFromDataStructure.o

# target to build an object file
core/data/distribution/DistributionFromDataStructure.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionFromDataStructure.cpp.o
.PHONY : core/data/distribution/DistributionFromDataStructure.cpp.o

core/data/distribution/DistributionFromDataStructure.i: core/data/distribution/DistributionFromDataStructure.cpp.i

.PHONY : core/data/distribution/DistributionFromDataStructure.i

# target to preprocess a source file
core/data/distribution/DistributionFromDataStructure.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionFromDataStructure.cpp.i
.PHONY : core/data/distribution/DistributionFromDataStructure.cpp.i

core/data/distribution/DistributionFromDataStructure.s: core/data/distribution/DistributionFromDataStructure.cpp.s

.PHONY : core/data/distribution/DistributionFromDataStructure.s

# target to generate assembly for a file
core/data/distribution/DistributionFromDataStructure.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionFromDataStructure.cpp.s
.PHONY : core/data/distribution/DistributionFromDataStructure.cpp.s

core/data/distribution/DistributionMultiVariate.o: core/data/distribution/DistributionMultiVariate.cpp.o

.PHONY : core/data/distribution/DistributionMultiVariate.o

# target to build an object file
core/data/distribution/DistributionMultiVariate.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariate.cpp.o
.PHONY : core/data/distribution/DistributionMultiVariate.cpp.o

core/data/distribution/DistributionMultiVariate.i: core/data/distribution/DistributionMultiVariate.cpp.i

.PHONY : core/data/distribution/DistributionMultiVariate.i

# target to preprocess a source file
core/data/distribution/DistributionMultiVariate.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariate.cpp.i
.PHONY : core/data/distribution/DistributionMultiVariate.cpp.i

core/data/distribution/DistributionMultiVariate.s: core/data/distribution/DistributionMultiVariate.cpp.s

.PHONY : core/data/distribution/DistributionMultiVariate.s

# target to generate assembly for a file
core/data/distribution/DistributionMultiVariate.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariate.cpp.s
.PHONY : core/data/distribution/DistributionMultiVariate.cpp.s

core/data/distribution/DistributionMultiVariateArithmetic.o: core/data/distribution/DistributionMultiVariateArithmetic.cpp.o

.PHONY : core/data/distribution/DistributionMultiVariateArithmetic.o

# target to build an object file
core/data/distribution/DistributionMultiVariateArithmetic.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariateArithmetic.cpp.o
.PHONY : core/data/distribution/DistributionMultiVariateArithmetic.cpp.o

core/data/distribution/DistributionMultiVariateArithmetic.i: core/data/distribution/DistributionMultiVariateArithmetic.cpp.i

.PHONY : core/data/distribution/DistributionMultiVariateArithmetic.i

# target to preprocess a source file
core/data/distribution/DistributionMultiVariateArithmetic.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariateArithmetic.cpp.i
.PHONY : core/data/distribution/DistributionMultiVariateArithmetic.cpp.i

core/data/distribution/DistributionMultiVariateArithmetic.s: core/data/distribution/DistributionMultiVariateArithmetic.cpp.s

.PHONY : core/data/distribution/DistributionMultiVariateArithmetic.s

# target to generate assembly for a file
core/data/distribution/DistributionMultiVariateArithmetic.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariateArithmetic.cpp.s
.PHONY : core/data/distribution/DistributionMultiVariateArithmetic.cpp.s

core/data/distribution/DistributionMultiVariateFromDataStructure.o: core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.o

.PHONY : core/data/distribution/DistributionMultiVariateFromDataStructure.o

# target to build an object file
core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.o
.PHONY : core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.o

core/data/distribution/DistributionMultiVariateFromDataStructure.i: core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.i

.PHONY : core/data/distribution/DistributionMultiVariateFromDataStructure.i

# target to preprocess a source file
core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.i
.PHONY : core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.i

core/data/distribution/DistributionMultiVariateFromDataStructure.s: core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.s

.PHONY : core/data/distribution/DistributionMultiVariateFromDataStructure.s

# target to generate assembly for a file
core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.s
.PHONY : core/data/distribution/DistributionMultiVariateFromDataStructure.cpp.s

core/data/germgrain/GermGrain.o: core/data/germgrain/GermGrain.cpp.o

.PHONY : core/data/germgrain/GermGrain.o

# target to build an object file
core/data/germgrain/GermGrain.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/germgrain/GermGrain.cpp.o
.PHONY : core/data/germgrain/GermGrain.cpp.o

core/data/germgrain/GermGrain.i: core/data/germgrain/GermGrain.cpp.i

.PHONY : core/data/germgrain/GermGrain.i

# target to preprocess a source file
core/data/germgrain/GermGrain.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/germgrain/GermGrain.cpp.i
.PHONY : core/data/germgrain/GermGrain.cpp.i

core/data/germgrain/GermGrain.s: core/data/germgrain/GermGrain.cpp.s

.PHONY : core/data/germgrain/GermGrain.s

# target to generate assembly for a file
core/data/germgrain/GermGrain.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/germgrain/GermGrain.cpp.s
.PHONY : core/data/germgrain/GermGrain.cpp.s

core/data/mat/MatNDisplay.o: core/data/mat/MatNDisplay.cpp.o

.PHONY : core/data/mat/MatNDisplay.o

# target to build an object file
core/data/mat/MatNDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNDisplay.cpp.o
.PHONY : core/data/mat/MatNDisplay.cpp.o

core/data/mat/MatNDisplay.i: core/data/mat/MatNDisplay.cpp.i

.PHONY : core/data/mat/MatNDisplay.i

# target to preprocess a source file
core/data/mat/MatNDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNDisplay.cpp.i
.PHONY : core/data/mat/MatNDisplay.cpp.i

core/data/mat/MatNDisplay.s: core/data/mat/MatNDisplay.cpp.s

.PHONY : core/data/mat/MatNDisplay.s

# target to generate assembly for a file
core/data/mat/MatNDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNDisplay.cpp.s
.PHONY : core/data/mat/MatNDisplay.cpp.s

core/data/mat/MatNInOut.o: core/data/mat/MatNInOut.cpp.o

.PHONY : core/data/mat/MatNInOut.o

# target to build an object file
core/data/mat/MatNInOut.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNInOut.cpp.o
.PHONY : core/data/mat/MatNInOut.cpp.o

core/data/mat/MatNInOut.i: core/data/mat/MatNInOut.cpp.i

.PHONY : core/data/mat/MatNInOut.i

# target to preprocess a source file
core/data/mat/MatNInOut.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNInOut.cpp.i
.PHONY : core/data/mat/MatNInOut.cpp.i

core/data/mat/MatNInOut.s: core/data/mat/MatNInOut.cpp.s

.PHONY : core/data/mat/MatNInOut.s

# target to generate assembly for a file
core/data/mat/MatNInOut.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNInOut.cpp.s
.PHONY : core/data/mat/MatNInOut.cpp.s

core/data/mat/MatNListType.o: core/data/mat/MatNListType.cpp.o

.PHONY : core/data/mat/MatNListType.o

# target to build an object file
core/data/mat/MatNListType.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNListType.cpp.o
.PHONY : core/data/mat/MatNListType.cpp.o

core/data/mat/MatNListType.i: core/data/mat/MatNListType.cpp.i

.PHONY : core/data/mat/MatNListType.i

# target to preprocess a source file
core/data/mat/MatNListType.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNListType.cpp.i
.PHONY : core/data/mat/MatNListType.cpp.i

core/data/mat/MatNListType.s: core/data/mat/MatNListType.cpp.s

.PHONY : core/data/mat/MatNListType.s

# target to generate assembly for a file
core/data/mat/MatNListType.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/mat/MatNListType.cpp.s
.PHONY : core/data/mat/MatNListType.cpp.s

core/data/neuralnetwork/NeuralNetwork.o: core/data/neuralnetwork/NeuralNetwork.cpp.o

.PHONY : core/data/neuralnetwork/NeuralNetwork.o

# target to build an object file
core/data/neuralnetwork/NeuralNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/neuralnetwork/NeuralNetwork.cpp.o
.PHONY : core/data/neuralnetwork/NeuralNetwork.cpp.o

core/data/neuralnetwork/NeuralNetwork.i: core/data/neuralnetwork/NeuralNetwork.cpp.i

.PHONY : core/data/neuralnetwork/NeuralNetwork.i

# target to preprocess a source file
core/data/neuralnetwork/NeuralNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/neuralnetwork/NeuralNetwork.cpp.i
.PHONY : core/data/neuralnetwork/NeuralNetwork.cpp.i

core/data/neuralnetwork/NeuralNetwork.s: core/data/neuralnetwork/NeuralNetwork.cpp.s

.PHONY : core/data/neuralnetwork/NeuralNetwork.s

# target to generate assembly for a file
core/data/neuralnetwork/NeuralNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/neuralnetwork/NeuralNetwork.cpp.s
.PHONY : core/data/neuralnetwork/NeuralNetwork.cpp.s

core/data/notstable/CharacteristicCluster.o: core/data/notstable/CharacteristicCluster.cpp.o

.PHONY : core/data/notstable/CharacteristicCluster.o

# target to build an object file
core/data/notstable/CharacteristicCluster.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/CharacteristicCluster.cpp.o
.PHONY : core/data/notstable/CharacteristicCluster.cpp.o

core/data/notstable/CharacteristicCluster.i: core/data/notstable/CharacteristicCluster.cpp.i

.PHONY : core/data/notstable/CharacteristicCluster.i

# target to preprocess a source file
core/data/notstable/CharacteristicCluster.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/CharacteristicCluster.cpp.i
.PHONY : core/data/notstable/CharacteristicCluster.cpp.i

core/data/notstable/CharacteristicCluster.s: core/data/notstable/CharacteristicCluster.cpp.s

.PHONY : core/data/notstable/CharacteristicCluster.s

# target to generate assembly for a file
core/data/notstable/CharacteristicCluster.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/CharacteristicCluster.cpp.s
.PHONY : core/data/notstable/CharacteristicCluster.cpp.s

core/data/notstable/Ransac.o: core/data/notstable/Ransac.cpp.o

.PHONY : core/data/notstable/Ransac.o

# target to build an object file
core/data/notstable/Ransac.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/Ransac.cpp.o
.PHONY : core/data/notstable/Ransac.cpp.o

core/data/notstable/Ransac.i: core/data/notstable/Ransac.cpp.i

.PHONY : core/data/notstable/Ransac.i

# target to preprocess a source file
core/data/notstable/Ransac.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/Ransac.cpp.i
.PHONY : core/data/notstable/Ransac.cpp.i

core/data/notstable/Ransac.s: core/data/notstable/Ransac.cpp.s

.PHONY : core/data/notstable/Ransac.s

# target to generate assembly for a file
core/data/notstable/Ransac.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/Ransac.cpp.s
.PHONY : core/data/notstable/Ransac.cpp.s

core/data/notstable/contour/Contour.o: core/data/notstable/contour/Contour.cpp.o

.PHONY : core/data/notstable/contour/Contour.o

# target to build an object file
core/data/notstable/contour/Contour.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/contour/Contour.cpp.o
.PHONY : core/data/notstable/contour/Contour.cpp.o

core/data/notstable/contour/Contour.i: core/data/notstable/contour/Contour.cpp.i

.PHONY : core/data/notstable/contour/Contour.i

# target to preprocess a source file
core/data/notstable/contour/Contour.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/contour/Contour.cpp.i
.PHONY : core/data/notstable/contour/Contour.cpp.i

core/data/notstable/contour/Contour.s: core/data/notstable/contour/Contour.cpp.s

.PHONY : core/data/notstable/contour/Contour.s

# target to generate assembly for a file
core/data/notstable/contour/Contour.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/contour/Contour.cpp.s
.PHONY : core/data/notstable/contour/Contour.cpp.s

core/data/notstable/graph/Edge.o: core/data/notstable/graph/Edge.cpp.o

.PHONY : core/data/notstable/graph/Edge.o

# target to build an object file
core/data/notstable/graph/Edge.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Edge.cpp.o
.PHONY : core/data/notstable/graph/Edge.cpp.o

core/data/notstable/graph/Edge.i: core/data/notstable/graph/Edge.cpp.i

.PHONY : core/data/notstable/graph/Edge.i

# target to preprocess a source file
core/data/notstable/graph/Edge.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Edge.cpp.i
.PHONY : core/data/notstable/graph/Edge.cpp.i

core/data/notstable/graph/Edge.s: core/data/notstable/graph/Edge.cpp.s

.PHONY : core/data/notstable/graph/Edge.s

# target to generate assembly for a file
core/data/notstable/graph/Edge.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Edge.cpp.s
.PHONY : core/data/notstable/graph/Edge.cpp.s

core/data/notstable/graph/Graph.o: core/data/notstable/graph/Graph.cpp.o

.PHONY : core/data/notstable/graph/Graph.o

# target to build an object file
core/data/notstable/graph/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Graph.cpp.o
.PHONY : core/data/notstable/graph/Graph.cpp.o

core/data/notstable/graph/Graph.i: core/data/notstable/graph/Graph.cpp.i

.PHONY : core/data/notstable/graph/Graph.i

# target to preprocess a source file
core/data/notstable/graph/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Graph.cpp.i
.PHONY : core/data/notstable/graph/Graph.cpp.i

core/data/notstable/graph/Graph.s: core/data/notstable/graph/Graph.cpp.s

.PHONY : core/data/notstable/graph/Graph.s

# target to generate assembly for a file
core/data/notstable/graph/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Graph.cpp.s
.PHONY : core/data/notstable/graph/Graph.cpp.s

core/data/notstable/graph/Vertex.o: core/data/notstable/graph/Vertex.cpp.o

.PHONY : core/data/notstable/graph/Vertex.o

# target to build an object file
core/data/notstable/graph/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Vertex.cpp.o
.PHONY : core/data/notstable/graph/Vertex.cpp.o

core/data/notstable/graph/Vertex.i: core/data/notstable/graph/Vertex.cpp.i

.PHONY : core/data/notstable/graph/Vertex.i

# target to preprocess a source file
core/data/notstable/graph/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Vertex.cpp.i
.PHONY : core/data/notstable/graph/Vertex.cpp.i

core/data/notstable/graph/Vertex.s: core/data/notstable/graph/Vertex.cpp.s

.PHONY : core/data/notstable/graph/Vertex.s

# target to generate assembly for a file
core/data/notstable/graph/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/notstable/graph/Vertex.cpp.s
.PHONY : core/data/notstable/graph/Vertex.cpp.s

core/data/ocr/OCR.o: core/data/ocr/OCR.cpp.o

.PHONY : core/data/ocr/OCR.o

# target to build an object file
core/data/ocr/OCR.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/ocr/OCR.cpp.o
.PHONY : core/data/ocr/OCR.cpp.o

core/data/ocr/OCR.i: core/data/ocr/OCR.cpp.i

.PHONY : core/data/ocr/OCR.i

# target to preprocess a source file
core/data/ocr/OCR.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/ocr/OCR.cpp.i
.PHONY : core/data/ocr/OCR.cpp.i

core/data/ocr/OCR.s: core/data/ocr/OCR.cpp.s

.PHONY : core/data/ocr/OCR.s

# target to generate assembly for a file
core/data/ocr/OCR.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/ocr/OCR.cpp.s
.PHONY : core/data/ocr/OCR.cpp.s

core/data/typeF/TypeTraitsF.o: core/data/typeF/TypeTraitsF.cpp.o

.PHONY : core/data/typeF/TypeTraitsF.o

# target to build an object file
core/data/typeF/TypeTraitsF.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/typeF/TypeTraitsF.cpp.o
.PHONY : core/data/typeF/TypeTraitsF.cpp.o

core/data/typeF/TypeTraitsF.i: core/data/typeF/TypeTraitsF.cpp.i

.PHONY : core/data/typeF/TypeTraitsF.i

# target to preprocess a source file
core/data/typeF/TypeTraitsF.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/typeF/TypeTraitsF.cpp.i
.PHONY : core/data/typeF/TypeTraitsF.cpp.i

core/data/typeF/TypeTraitsF.s: core/data/typeF/TypeTraitsF.cpp.s

.PHONY : core/data/typeF/TypeTraitsF.s

# target to generate assembly for a file
core/data/typeF/TypeTraitsF.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/typeF/TypeTraitsF.cpp.s
.PHONY : core/data/typeF/TypeTraitsF.cpp.s

core/data/utility/BasicUtility.o: core/data/utility/BasicUtility.cpp.o

.PHONY : core/data/utility/BasicUtility.o

# target to build an object file
core/data/utility/BasicUtility.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/BasicUtility.cpp.o
.PHONY : core/data/utility/BasicUtility.cpp.o

core/data/utility/BasicUtility.i: core/data/utility/BasicUtility.cpp.i

.PHONY : core/data/utility/BasicUtility.i

# target to preprocess a source file
core/data/utility/BasicUtility.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/BasicUtility.cpp.i
.PHONY : core/data/utility/BasicUtility.cpp.i

core/data/utility/BasicUtility.s: core/data/utility/BasicUtility.cpp.s

.PHONY : core/data/utility/BasicUtility.s

# target to generate assembly for a file
core/data/utility/BasicUtility.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/BasicUtility.cpp.s
.PHONY : core/data/utility/BasicUtility.cpp.s

core/data/utility/CollectorExecutionInformation.o: core/data/utility/CollectorExecutionInformation.cpp.o

.PHONY : core/data/utility/CollectorExecutionInformation.o

# target to build an object file
core/data/utility/CollectorExecutionInformation.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/CollectorExecutionInformation.cpp.o
.PHONY : core/data/utility/CollectorExecutionInformation.cpp.o

core/data/utility/CollectorExecutionInformation.i: core/data/utility/CollectorExecutionInformation.cpp.i

.PHONY : core/data/utility/CollectorExecutionInformation.i

# target to preprocess a source file
core/data/utility/CollectorExecutionInformation.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/CollectorExecutionInformation.cpp.i
.PHONY : core/data/utility/CollectorExecutionInformation.cpp.i

core/data/utility/CollectorExecutionInformation.s: core/data/utility/CollectorExecutionInformation.cpp.s

.PHONY : core/data/utility/CollectorExecutionInformation.s

# target to generate assembly for a file
core/data/utility/CollectorExecutionInformation.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/CollectorExecutionInformation.cpp.s
.PHONY : core/data/utility/CollectorExecutionInformation.cpp.s

core/data/utility/Exception.o: core/data/utility/Exception.cpp.o

.PHONY : core/data/utility/Exception.o

# target to build an object file
core/data/utility/Exception.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/Exception.cpp.o
.PHONY : core/data/utility/Exception.cpp.o

core/data/utility/Exception.i: core/data/utility/Exception.cpp.i

.PHONY : core/data/utility/Exception.i

# target to preprocess a source file
core/data/utility/Exception.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/Exception.cpp.i
.PHONY : core/data/utility/Exception.cpp.i

core/data/utility/Exception.s: core/data/utility/Exception.cpp.s

.PHONY : core/data/utility/Exception.s

# target to generate assembly for a file
core/data/utility/Exception.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/Exception.cpp.s
.PHONY : core/data/utility/Exception.cpp.s

core/data/utility/XML.o: core/data/utility/XML.cpp.o

.PHONY : core/data/utility/XML.o

# target to build an object file
core/data/utility/XML.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/XML.cpp.o
.PHONY : core/data/utility/XML.cpp.o

core/data/utility/XML.i: core/data/utility/XML.cpp.i

.PHONY : core/data/utility/XML.i

# target to preprocess a source file
core/data/utility/XML.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/XML.cpp.i
.PHONY : core/data/utility/XML.cpp.i

core/data/utility/XML.s: core/data/utility/XML.cpp.s

.PHONY : core/data/utility/XML.s

# target to generate assembly for a file
core/data/utility/XML.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/utility/XML.cpp.s
.PHONY : core/data/utility/XML.cpp.s

core/data/video/Video.o: core/data/video/Video.cpp.o

.PHONY : core/data/video/Video.o

# target to build an object file
core/data/video/Video.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/video/Video.cpp.o
.PHONY : core/data/video/Video.cpp.o

core/data/video/Video.i: core/data/video/Video.cpp.i

.PHONY : core/data/video/Video.i

# target to preprocess a source file
core/data/video/Video.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/video/Video.cpp.i
.PHONY : core/data/video/Video.cpp.i

core/data/video/Video.s: core/data/video/Video.cpp.s

.PHONY : core/data/video/Video.s

# target to generate assembly for a file
core/data/video/Video.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/data/video/Video.cpp.s
.PHONY : core/data/video/Video.cpp.s

core/dependency/MTRand.o: core/dependency/MTRand.cpp.o

.PHONY : core/dependency/MTRand.o

# target to build an object file
core/dependency/MTRand.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/MTRand.cpp.o
.PHONY : core/dependency/MTRand.cpp.o

core/dependency/MTRand.i: core/dependency/MTRand.cpp.i

.PHONY : core/dependency/MTRand.i

# target to preprocess a source file
core/dependency/MTRand.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/MTRand.cpp.i
.PHONY : core/dependency/MTRand.cpp.i

core/dependency/MTRand.s: core/dependency/MTRand.cpp.s

.PHONY : core/dependency/MTRand.s

# target to generate assembly for a file
core/dependency/MTRand.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/MTRand.cpp.s
.PHONY : core/dependency/MTRand.cpp.s

core/dependency/fparser.o: core/dependency/fparser.cpp.o

.PHONY : core/dependency/fparser.o

# target to build an object file
core/dependency/fparser.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/fparser.cpp.o
.PHONY : core/dependency/fparser.cpp.o

core/dependency/fparser.i: core/dependency/fparser.cpp.i

.PHONY : core/dependency/fparser.i

# target to preprocess a source file
core/dependency/fparser.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/fparser.cpp.i
.PHONY : core/dependency/fparser.cpp.i

core/dependency/fparser.s: core/dependency/fparser.cpp.s

.PHONY : core/dependency/fparser.s

# target to generate assembly for a file
core/dependency/fparser.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/fparser.cpp.s
.PHONY : core/dependency/fparser.cpp.s

core/dependency/jpgd.o: core/dependency/jpgd.cpp.o

.PHONY : core/dependency/jpgd.o

# target to build an object file
core/dependency/jpgd.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/jpgd.cpp.o
.PHONY : core/dependency/jpgd.cpp.o

core/dependency/jpgd.i: core/dependency/jpgd.cpp.i

.PHONY : core/dependency/jpgd.i

# target to preprocess a source file
core/dependency/jpgd.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/jpgd.cpp.i
.PHONY : core/dependency/jpgd.cpp.i

core/dependency/jpgd.s: core/dependency/jpgd.cpp.s

.PHONY : core/dependency/jpgd.s

# target to generate assembly for a file
core/dependency/jpgd.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/jpgd.cpp.s
.PHONY : core/dependency/jpgd.cpp.s

core/dependency/jpge.o: core/dependency/jpge.cpp.o

.PHONY : core/dependency/jpge.o

# target to build an object file
core/dependency/jpge.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/jpge.cpp.o
.PHONY : core/dependency/jpge.cpp.o

core/dependency/jpge.i: core/dependency/jpge.cpp.i

.PHONY : core/dependency/jpge.i

# target to preprocess a source file
core/dependency/jpge.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/jpge.cpp.i
.PHONY : core/dependency/jpge.cpp.i

core/dependency/jpge.s: core/dependency/jpge.cpp.s

.PHONY : core/dependency/jpge.s

# target to generate assembly for a file
core/dependency/jpge.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/jpge.cpp.s
.PHONY : core/dependency/jpge.cpp.s

core/dependency/lodepng.o: core/dependency/lodepng.cpp.o

.PHONY : core/dependency/lodepng.o

# target to build an object file
core/dependency/lodepng.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/lodepng.cpp.o
.PHONY : core/dependency/lodepng.cpp.o

core/dependency/lodepng.i: core/dependency/lodepng.cpp.i

.PHONY : core/dependency/lodepng.i

# target to preprocess a source file
core/dependency/lodepng.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/lodepng.cpp.i
.PHONY : core/dependency/lodepng.cpp.i

core/dependency/lodepng.s: core/dependency/lodepng.cpp.s

.PHONY : core/dependency/lodepng.s

# target to generate assembly for a file
core/dependency/lodepng.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/lodepng.cpp.s
.PHONY : core/dependency/lodepng.cpp.s

core/dependency/pugixml.o: core/dependency/pugixml.cpp.o

.PHONY : core/dependency/pugixml.o

# target to build an object file
core/dependency/pugixml.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/pugixml.cpp.o
.PHONY : core/dependency/pugixml.cpp.o

core/dependency/pugixml.i: core/dependency/pugixml.cpp.i

.PHONY : core/dependency/pugixml.i

# target to preprocess a source file
core/dependency/pugixml.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/pugixml.cpp.i
.PHONY : core/dependency/pugixml.cpp.i

core/dependency/pugixml.s: core/dependency/pugixml.cpp.s

.PHONY : core/dependency/pugixml.s

# target to generate assembly for a file
core/dependency/pugixml.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/pugixml.cpp.s
.PHONY : core/dependency/pugixml.cpp.s

core/dependency/tinythread.o: core/dependency/tinythread.cpp.o

.PHONY : core/dependency/tinythread.o

# target to build an object file
core/dependency/tinythread.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/tinythread.cpp.o
.PHONY : core/dependency/tinythread.cpp.o

core/dependency/tinythread.i: core/dependency/tinythread.cpp.i

.PHONY : core/dependency/tinythread.i

# target to preprocess a source file
core/dependency/tinythread.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/tinythread.cpp.i
.PHONY : core/dependency/tinythread.cpp.i

core/dependency/tinythread.s: core/dependency/tinythread.cpp.s

.PHONY : core/dependency/tinythread.s

# target to generate assembly for a file
core/dependency/tinythread.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/core/dependency/tinythread.cpp.s
.PHONY : core/dependency/tinythread.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/main.cpp.s
.PHONY : main.cpp.s

population_sacha/Calculate_percentage_of_a_color_on_contours.o: population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.o

.PHONY : population_sacha/Calculate_percentage_of_a_color_on_contours.o

# target to build an object file
population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.o
.PHONY : population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.o

population_sacha/Calculate_percentage_of_a_color_on_contours.i: population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.i

.PHONY : population_sacha/Calculate_percentage_of_a_color_on_contours.i

# target to preprocess a source file
population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.i
.PHONY : population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.i

population_sacha/Calculate_percentage_of_a_color_on_contours.s: population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.s

.PHONY : population_sacha/Calculate_percentage_of_a_color_on_contours.s

# target to generate assembly for a file
population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.s
.PHONY : population_sacha/Calculate_percentage_of_a_color_on_contours.cpp.s

population_sacha/Choose_input_folder.o: population_sacha/Choose_input_folder.cpp.o

.PHONY : population_sacha/Choose_input_folder.o

# target to build an object file
population_sacha/Choose_input_folder.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Choose_input_folder.cpp.o
.PHONY : population_sacha/Choose_input_folder.cpp.o

population_sacha/Choose_input_folder.i: population_sacha/Choose_input_folder.cpp.i

.PHONY : population_sacha/Choose_input_folder.i

# target to preprocess a source file
population_sacha/Choose_input_folder.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Choose_input_folder.cpp.i
.PHONY : population_sacha/Choose_input_folder.cpp.i

population_sacha/Choose_input_folder.s: population_sacha/Choose_input_folder.cpp.s

.PHONY : population_sacha/Choose_input_folder.s

# target to generate assembly for a file
population_sacha/Choose_input_folder.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Choose_input_folder.cpp.s
.PHONY : population_sacha/Choose_input_folder.cpp.s

population_sacha/Close_regions.o: population_sacha/Close_regions.cpp.o

.PHONY : population_sacha/Close_regions.o

# target to build an object file
population_sacha/Close_regions.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Close_regions.cpp.o
.PHONY : population_sacha/Close_regions.cpp.o

population_sacha/Close_regions.i: population_sacha/Close_regions.cpp.i

.PHONY : population_sacha/Close_regions.i

# target to preprocess a source file
population_sacha/Close_regions.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Close_regions.cpp.i
.PHONY : population_sacha/Close_regions.cpp.i

population_sacha/Close_regions.s: population_sacha/Close_regions.cpp.s

.PHONY : population_sacha/Close_regions.s

# target to generate assembly for a file
population_sacha/Close_regions.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Close_regions.cpp.s
.PHONY : population_sacha/Close_regions.cpp.s

population_sacha/Copy_original_image.o: population_sacha/Copy_original_image.cpp.o

.PHONY : population_sacha/Copy_original_image.o

# target to build an object file
population_sacha/Copy_original_image.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Copy_original_image.cpp.o
.PHONY : population_sacha/Copy_original_image.cpp.o

population_sacha/Copy_original_image.i: population_sacha/Copy_original_image.cpp.i

.PHONY : population_sacha/Copy_original_image.i

# target to preprocess a source file
population_sacha/Copy_original_image.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Copy_original_image.cpp.i
.PHONY : population_sacha/Copy_original_image.cpp.i

population_sacha/Copy_original_image.s: population_sacha/Copy_original_image.cpp.s

.PHONY : population_sacha/Copy_original_image.s

# target to generate assembly for a file
population_sacha/Copy_original_image.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Copy_original_image.cpp.s
.PHONY : population_sacha/Copy_original_image.cpp.s

population_sacha/Create_dot_finished_file.o: population_sacha/Create_dot_finished_file.cpp.o

.PHONY : population_sacha/Create_dot_finished_file.o

# target to build an object file
population_sacha/Create_dot_finished_file.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Create_dot_finished_file.cpp.o
.PHONY : population_sacha/Create_dot_finished_file.cpp.o

population_sacha/Create_dot_finished_file.i: population_sacha/Create_dot_finished_file.cpp.i

.PHONY : population_sacha/Create_dot_finished_file.i

# target to preprocess a source file
population_sacha/Create_dot_finished_file.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Create_dot_finished_file.cpp.i
.PHONY : population_sacha/Create_dot_finished_file.cpp.i

population_sacha/Create_dot_finished_file.s: population_sacha/Create_dot_finished_file.cpp.s

.PHONY : population_sacha/Create_dot_finished_file.s

# target to generate assembly for a file
population_sacha/Create_dot_finished_file.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Create_dot_finished_file.cpp.s
.PHONY : population_sacha/Create_dot_finished_file.cpp.s

population_sacha/Create_results_folder.o: population_sacha/Create_results_folder.cpp.o

.PHONY : population_sacha/Create_results_folder.o

# target to build an object file
population_sacha/Create_results_folder.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Create_results_folder.cpp.o
.PHONY : population_sacha/Create_results_folder.cpp.o

population_sacha/Create_results_folder.i: population_sacha/Create_results_folder.cpp.i

.PHONY : population_sacha/Create_results_folder.i

# target to preprocess a source file
population_sacha/Create_results_folder.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Create_results_folder.cpp.i
.PHONY : population_sacha/Create_results_folder.cpp.i

population_sacha/Create_results_folder.s: population_sacha/Create_results_folder.cpp.s

.PHONY : population_sacha/Create_results_folder.s

# target to generate assembly for a file
population_sacha/Create_results_folder.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Create_results_folder.cpp.s
.PHONY : population_sacha/Create_results_folder.cpp.s

population_sacha/Discriminate_capillaries_from_IVS.o: population_sacha/Discriminate_capillaries_from_IVS.cpp.o

.PHONY : population_sacha/Discriminate_capillaries_from_IVS.o

# target to build an object file
population_sacha/Discriminate_capillaries_from_IVS.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Discriminate_capillaries_from_IVS.cpp.o
.PHONY : population_sacha/Discriminate_capillaries_from_IVS.cpp.o

population_sacha/Discriminate_capillaries_from_IVS.i: population_sacha/Discriminate_capillaries_from_IVS.cpp.i

.PHONY : population_sacha/Discriminate_capillaries_from_IVS.i

# target to preprocess a source file
population_sacha/Discriminate_capillaries_from_IVS.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Discriminate_capillaries_from_IVS.cpp.i
.PHONY : population_sacha/Discriminate_capillaries_from_IVS.cpp.i

population_sacha/Discriminate_capillaries_from_IVS.s: population_sacha/Discriminate_capillaries_from_IVS.cpp.s

.PHONY : population_sacha/Discriminate_capillaries_from_IVS.s

# target to generate assembly for a file
population_sacha/Discriminate_capillaries_from_IVS.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Discriminate_capillaries_from_IVS.cpp.s
.PHONY : population_sacha/Discriminate_capillaries_from_IVS.cpp.s

population_sacha/Estimate_villi_density.o: population_sacha/Estimate_villi_density.cpp.o

.PHONY : population_sacha/Estimate_villi_density.o

# target to build an object file
population_sacha/Estimate_villi_density.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Estimate_villi_density.cpp.o
.PHONY : population_sacha/Estimate_villi_density.cpp.o

population_sacha/Estimate_villi_density.i: population_sacha/Estimate_villi_density.cpp.i

.PHONY : population_sacha/Estimate_villi_density.i

# target to preprocess a source file
population_sacha/Estimate_villi_density.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Estimate_villi_density.cpp.i
.PHONY : population_sacha/Estimate_villi_density.cpp.i

population_sacha/Estimate_villi_density.s: population_sacha/Estimate_villi_density.cpp.s

.PHONY : population_sacha/Estimate_villi_density.s

# target to generate assembly for a file
population_sacha/Estimate_villi_density.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Estimate_villi_density.cpp.s
.PHONY : population_sacha/Estimate_villi_density.cpp.s

population_sacha/Extract_contours.o: population_sacha/Extract_contours.cpp.o

.PHONY : population_sacha/Extract_contours.o

# target to build an object file
population_sacha/Extract_contours.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Extract_contours.cpp.o
.PHONY : population_sacha/Extract_contours.cpp.o

population_sacha/Extract_contours.i: population_sacha/Extract_contours.cpp.i

.PHONY : population_sacha/Extract_contours.i

# target to preprocess a source file
population_sacha/Extract_contours.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Extract_contours.cpp.i
.PHONY : population_sacha/Extract_contours.cpp.i

population_sacha/Extract_contours.s: population_sacha/Extract_contours.cpp.s

.PHONY : population_sacha/Extract_contours.s

# target to generate assembly for a file
population_sacha/Extract_contours.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Extract_contours.cpp.s
.PHONY : population_sacha/Extract_contours.cpp.s

population_sacha/Find_thresholds_for_a_matrix.o: population_sacha/Find_thresholds_for_a_matrix.cpp.o

.PHONY : population_sacha/Find_thresholds_for_a_matrix.o

# target to build an object file
population_sacha/Find_thresholds_for_a_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Find_thresholds_for_a_matrix.cpp.o
.PHONY : population_sacha/Find_thresholds_for_a_matrix.cpp.o

population_sacha/Find_thresholds_for_a_matrix.i: population_sacha/Find_thresholds_for_a_matrix.cpp.i

.PHONY : population_sacha/Find_thresholds_for_a_matrix.i

# target to preprocess a source file
population_sacha/Find_thresholds_for_a_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Find_thresholds_for_a_matrix.cpp.i
.PHONY : population_sacha/Find_thresholds_for_a_matrix.cpp.i

population_sacha/Find_thresholds_for_a_matrix.s: population_sacha/Find_thresholds_for_a_matrix.cpp.s

.PHONY : population_sacha/Find_thresholds_for_a_matrix.s

# target to generate assembly for a file
population_sacha/Find_thresholds_for_a_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Find_thresholds_for_a_matrix.cpp.s
.PHONY : population_sacha/Find_thresholds_for_a_matrix.cpp.s

population_sacha/Initial_segmentation.o: population_sacha/Initial_segmentation.cpp.o

.PHONY : population_sacha/Initial_segmentation.o

# target to build an object file
population_sacha/Initial_segmentation.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Initial_segmentation.cpp.o
.PHONY : population_sacha/Initial_segmentation.cpp.o

population_sacha/Initial_segmentation.i: population_sacha/Initial_segmentation.cpp.i

.PHONY : population_sacha/Initial_segmentation.i

# target to preprocess a source file
population_sacha/Initial_segmentation.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Initial_segmentation.cpp.i
.PHONY : population_sacha/Initial_segmentation.cpp.i

population_sacha/Initial_segmentation.s: population_sacha/Initial_segmentation.cpp.s

.PHONY : population_sacha/Initial_segmentation.s

# target to generate assembly for a file
population_sacha/Initial_segmentation.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Initial_segmentation.cpp.s
.PHONY : population_sacha/Initial_segmentation.cpp.s

population_sacha/Load_placenta_picture.o: population_sacha/Load_placenta_picture.cpp.o

.PHONY : population_sacha/Load_placenta_picture.o

# target to build an object file
population_sacha/Load_placenta_picture.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Load_placenta_picture.cpp.o
.PHONY : population_sacha/Load_placenta_picture.cpp.o

population_sacha/Load_placenta_picture.i: population_sacha/Load_placenta_picture.cpp.i

.PHONY : population_sacha/Load_placenta_picture.i

# target to preprocess a source file
population_sacha/Load_placenta_picture.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Load_placenta_picture.cpp.i
.PHONY : population_sacha/Load_placenta_picture.cpp.i

population_sacha/Load_placenta_picture.s: population_sacha/Load_placenta_picture.cpp.s

.PHONY : population_sacha/Load_placenta_picture.s

# target to generate assembly for a file
population_sacha/Load_placenta_picture.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Load_placenta_picture.cpp.s
.PHONY : population_sacha/Load_placenta_picture.cpp.s

population_sacha/Log_steps.o: population_sacha/Log_steps.cpp.o

.PHONY : population_sacha/Log_steps.o

# target to build an object file
population_sacha/Log_steps.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Log_steps.cpp.o
.PHONY : population_sacha/Log_steps.cpp.o

population_sacha/Log_steps.i: population_sacha/Log_steps.cpp.i

.PHONY : population_sacha/Log_steps.i

# target to preprocess a source file
population_sacha/Log_steps.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Log_steps.cpp.i
.PHONY : population_sacha/Log_steps.cpp.i

population_sacha/Log_steps.s: population_sacha/Log_steps.cpp.s

.PHONY : population_sacha/Log_steps.s

# target to generate assembly for a file
population_sacha/Log_steps.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Log_steps.cpp.s
.PHONY : population_sacha/Log_steps.cpp.s

population_sacha/Open_regions.o: population_sacha/Open_regions.cpp.o

.PHONY : population_sacha/Open_regions.o

# target to build an object file
population_sacha/Open_regions.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Open_regions.cpp.o
.PHONY : population_sacha/Open_regions.cpp.o

population_sacha/Open_regions.i: population_sacha/Open_regions.cpp.i

.PHONY : population_sacha/Open_regions.i

# target to preprocess a source file
population_sacha/Open_regions.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Open_regions.cpp.i
.PHONY : population_sacha/Open_regions.cpp.i

population_sacha/Open_regions.s: population_sacha/Open_regions.cpp.s

.PHONY : population_sacha/Open_regions.s

# target to generate assembly for a file
population_sacha/Open_regions.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Open_regions.cpp.s
.PHONY : population_sacha/Open_regions.cpp.s

population_sacha/Output_statistics.o: population_sacha/Output_statistics.cpp.o

.PHONY : population_sacha/Output_statistics.o

# target to build an object file
population_sacha/Output_statistics.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Output_statistics.cpp.o
.PHONY : population_sacha/Output_statistics.cpp.o

population_sacha/Output_statistics.i: population_sacha/Output_statistics.cpp.i

.PHONY : population_sacha/Output_statistics.i

# target to preprocess a source file
population_sacha/Output_statistics.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Output_statistics.cpp.i
.PHONY : population_sacha/Output_statistics.cpp.i

population_sacha/Output_statistics.s: population_sacha/Output_statistics.cpp.s

.PHONY : population_sacha/Output_statistics.s

# target to generate assembly for a file
population_sacha/Output_statistics.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Output_statistics.cpp.s
.PHONY : population_sacha/Output_statistics.cpp.s

population_sacha/Read_next_image.o: population_sacha/Read_next_image.cpp.o

.PHONY : population_sacha/Read_next_image.o

# target to build an object file
population_sacha/Read_next_image.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Read_next_image.cpp.o
.PHONY : population_sacha/Read_next_image.cpp.o

population_sacha/Read_next_image.i: population_sacha/Read_next_image.cpp.i

.PHONY : population_sacha/Read_next_image.i

# target to preprocess a source file
population_sacha/Read_next_image.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Read_next_image.cpp.i
.PHONY : population_sacha/Read_next_image.cpp.i

population_sacha/Read_next_image.s: population_sacha/Read_next_image.cpp.s

.PHONY : population_sacha/Read_next_image.s

# target to generate assembly for a file
population_sacha/Read_next_image.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Read_next_image.cpp.s
.PHONY : population_sacha/Read_next_image.cpp.s

population_sacha/Remove_IVS_and_villous_regions_by_area.o: population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.o

.PHONY : population_sacha/Remove_IVS_and_villous_regions_by_area.o

# target to build an object file
population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.o
.PHONY : population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.o

population_sacha/Remove_IVS_and_villous_regions_by_area.i: population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.i

.PHONY : population_sacha/Remove_IVS_and_villous_regions_by_area.i

# target to preprocess a source file
population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.i
.PHONY : population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.i

population_sacha/Remove_IVS_and_villous_regions_by_area.s: population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.s

.PHONY : population_sacha/Remove_IVS_and_villous_regions_by_area.s

# target to generate assembly for a file
population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.s
.PHONY : population_sacha/Remove_IVS_and_villous_regions_by_area.cpp.s

population_sacha/Remove_IVS_inside_villi.o: population_sacha/Remove_IVS_inside_villi.cpp.o

.PHONY : population_sacha/Remove_IVS_inside_villi.o

# target to build an object file
population_sacha/Remove_IVS_inside_villi.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Remove_IVS_inside_villi.cpp.o
.PHONY : population_sacha/Remove_IVS_inside_villi.cpp.o

population_sacha/Remove_IVS_inside_villi.i: population_sacha/Remove_IVS_inside_villi.cpp.i

.PHONY : population_sacha/Remove_IVS_inside_villi.i

# target to preprocess a source file
population_sacha/Remove_IVS_inside_villi.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Remove_IVS_inside_villi.cpp.i
.PHONY : population_sacha/Remove_IVS_inside_villi.cpp.i

population_sacha/Remove_IVS_inside_villi.s: population_sacha/Remove_IVS_inside_villi.cpp.s

.PHONY : population_sacha/Remove_IVS_inside_villi.s

# target to generate assembly for a file
population_sacha/Remove_IVS_inside_villi.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Remove_IVS_inside_villi.cpp.s
.PHONY : population_sacha/Remove_IVS_inside_villi.cpp.s

population_sacha/Small_functions.o: population_sacha/Small_functions.cpp.o

.PHONY : population_sacha/Small_functions.o

# target to build an object file
population_sacha/Small_functions.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Small_functions.cpp.o
.PHONY : population_sacha/Small_functions.cpp.o

population_sacha/Small_functions.i: population_sacha/Small_functions.cpp.i

.PHONY : population_sacha/Small_functions.i

# target to preprocess a source file
population_sacha/Small_functions.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Small_functions.cpp.i
.PHONY : population_sacha/Small_functions.cpp.i

population_sacha/Small_functions.s: population_sacha/Small_functions.cpp.s

.PHONY : population_sacha/Small_functions.s

# target to generate assembly for a file
population_sacha/Small_functions.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Small_functions.cpp.s
.PHONY : population_sacha/Small_functions.cpp.s

population_sacha/Smooth_out_the_contours.o: population_sacha/Smooth_out_the_contours.cpp.o

.PHONY : population_sacha/Smooth_out_the_contours.o

# target to build an object file
population_sacha/Smooth_out_the_contours.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Smooth_out_the_contours.cpp.o
.PHONY : population_sacha/Smooth_out_the_contours.cpp.o

population_sacha/Smooth_out_the_contours.i: population_sacha/Smooth_out_the_contours.cpp.i

.PHONY : population_sacha/Smooth_out_the_contours.i

# target to preprocess a source file
population_sacha/Smooth_out_the_contours.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Smooth_out_the_contours.cpp.i
.PHONY : population_sacha/Smooth_out_the_contours.cpp.i

population_sacha/Smooth_out_the_contours.s: population_sacha/Smooth_out_the_contours.cpp.s

.PHONY : population_sacha/Smooth_out_the_contours.s

# target to generate assembly for a file
population_sacha/Smooth_out_the_contours.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Smooth_out_the_contours.cpp.s
.PHONY : population_sacha/Smooth_out_the_contours.cpp.s

population_sacha/Statistics_placenta.o: population_sacha/Statistics_placenta.cpp.o

.PHONY : population_sacha/Statistics_placenta.o

# target to build an object file
population_sacha/Statistics_placenta.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Statistics_placenta.cpp.o
.PHONY : population_sacha/Statistics_placenta.cpp.o

population_sacha/Statistics_placenta.i: population_sacha/Statistics_placenta.cpp.i

.PHONY : population_sacha/Statistics_placenta.i

# target to preprocess a source file
population_sacha/Statistics_placenta.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Statistics_placenta.cpp.i
.PHONY : population_sacha/Statistics_placenta.cpp.i

population_sacha/Statistics_placenta.s: population_sacha/Statistics_placenta.cpp.s

.PHONY : population_sacha/Statistics_placenta.s

# target to generate assembly for a file
population_sacha/Statistics_placenta.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/Statistics_placenta.cpp.s
.PHONY : population_sacha/Statistics_placenta.cpp.s

population_sacha/class_RLE_Image.o: population_sacha/class_RLE_Image.cpp.o

.PHONY : population_sacha/class_RLE_Image.o

# target to build an object file
population_sacha/class_RLE_Image.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/class_RLE_Image.cpp.o
.PHONY : population_sacha/class_RLE_Image.cpp.o

population_sacha/class_RLE_Image.i: population_sacha/class_RLE_Image.cpp.i

.PHONY : population_sacha/class_RLE_Image.i

# target to preprocess a source file
population_sacha/class_RLE_Image.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/class_RLE_Image.cpp.i
.PHONY : population_sacha/class_RLE_Image.cpp.i

population_sacha/class_RLE_Image.s: population_sacha/class_RLE_Image.cpp.s

.PHONY : population_sacha/class_RLE_Image.s

# target to generate assembly for a file
population_sacha/class_RLE_Image.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/class_RLE_Image.cpp.s
.PHONY : population_sacha/class_RLE_Image.cpp.s

population_sacha/class_Run.o: population_sacha/class_Run.cpp.o

.PHONY : population_sacha/class_Run.o

# target to build an object file
population_sacha/class_Run.cpp.o:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/class_Run.cpp.o
.PHONY : population_sacha/class_Run.cpp.o

population_sacha/class_Run.i: population_sacha/class_Run.cpp.i

.PHONY : population_sacha/class_Run.i

# target to preprocess a source file
population_sacha/class_Run.cpp.i:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/class_Run.cpp.i
.PHONY : population_sacha/class_Run.cpp.i

population_sacha/class_Run.s: population_sacha/class_Run.cpp.s

.PHONY : population_sacha/class_Run.s

# target to generate assembly for a file
population_sacha/class_Run.cpp.s:
	$(MAKE) -f CMakeFiles/Human_placenta.dir/build.make CMakeFiles/Human_placenta.dir/population_sacha/class_Run.cpp.s
.PHONY : population_sacha/class_Run.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Human_placenta"
	@echo "... core/algorithm/GeometricalTransformation.o"
	@echo "... core/algorithm/GeometricalTransformation.i"
	@echo "... core/algorithm/GeometricalTransformation.s"
	@echo "... core/algorithm/LinearAlgebra.o"
	@echo "... core/algorithm/LinearAlgebra.i"
	@echo "... core/algorithm/LinearAlgebra.s"
	@echo "... core/algorithm/RandomGeometry.o"
	@echo "... core/algorithm/RandomGeometry.i"
	@echo "... core/algorithm/RandomGeometry.s"
	@echo "... core/algorithm/Statistics.o"
	@echo "... core/algorithm/Statistics.i"
	@echo "... core/algorithm/Statistics.s"
	@echo "... core/algorithm/Visualization.o"
	@echo "... core/algorithm/Visualization.i"
	@echo "... core/algorithm/Visualization.s"
	@echo "... core/data/3d/GLFigure.o"
	@echo "... core/data/3d/GLFigure.i"
	@echo "... core/data/3d/GLFigure.s"
	@echo "... core/data/distribution/Distribution.o"
	@echo "... core/data/distribution/Distribution.i"
	@echo "... core/data/distribution/Distribution.s"
	@echo "... core/data/distribution/DistributionAnalytic.o"
	@echo "... core/data/distribution/DistributionAnalytic.i"
	@echo "... core/data/distribution/DistributionAnalytic.s"
	@echo "... core/data/distribution/DistributionArithmetic.o"
	@echo "... core/data/distribution/DistributionArithmetic.i"
	@echo "... core/data/distribution/DistributionArithmetic.s"
	@echo "... core/data/distribution/DistributionFromDataStructure.o"
	@echo "... core/data/distribution/DistributionFromDataStructure.i"
	@echo "... core/data/distribution/DistributionFromDataStructure.s"
	@echo "... core/data/distribution/DistributionMultiVariate.o"
	@echo "... core/data/distribution/DistributionMultiVariate.i"
	@echo "... core/data/distribution/DistributionMultiVariate.s"
	@echo "... core/data/distribution/DistributionMultiVariateArithmetic.o"
	@echo "... core/data/distribution/DistributionMultiVariateArithmetic.i"
	@echo "... core/data/distribution/DistributionMultiVariateArithmetic.s"
	@echo "... core/data/distribution/DistributionMultiVariateFromDataStructure.o"
	@echo "... core/data/distribution/DistributionMultiVariateFromDataStructure.i"
	@echo "... core/data/distribution/DistributionMultiVariateFromDataStructure.s"
	@echo "... core/data/germgrain/GermGrain.o"
	@echo "... core/data/germgrain/GermGrain.i"
	@echo "... core/data/germgrain/GermGrain.s"
	@echo "... core/data/mat/MatNDisplay.o"
	@echo "... core/data/mat/MatNDisplay.i"
	@echo "... core/data/mat/MatNDisplay.s"
	@echo "... core/data/mat/MatNInOut.o"
	@echo "... core/data/mat/MatNInOut.i"
	@echo "... core/data/mat/MatNInOut.s"
	@echo "... core/data/mat/MatNListType.o"
	@echo "... core/data/mat/MatNListType.i"
	@echo "... core/data/mat/MatNListType.s"
	@echo "... core/data/neuralnetwork/NeuralNetwork.o"
	@echo "... core/data/neuralnetwork/NeuralNetwork.i"
	@echo "... core/data/neuralnetwork/NeuralNetwork.s"
	@echo "... core/data/notstable/CharacteristicCluster.o"
	@echo "... core/data/notstable/CharacteristicCluster.i"
	@echo "... core/data/notstable/CharacteristicCluster.s"
	@echo "... core/data/notstable/Ransac.o"
	@echo "... core/data/notstable/Ransac.i"
	@echo "... core/data/notstable/Ransac.s"
	@echo "... core/data/notstable/contour/Contour.o"
	@echo "... core/data/notstable/contour/Contour.i"
	@echo "... core/data/notstable/contour/Contour.s"
	@echo "... core/data/notstable/graph/Edge.o"
	@echo "... core/data/notstable/graph/Edge.i"
	@echo "... core/data/notstable/graph/Edge.s"
	@echo "... core/data/notstable/graph/Graph.o"
	@echo "... core/data/notstable/graph/Graph.i"
	@echo "... core/data/notstable/graph/Graph.s"
	@echo "... core/data/notstable/graph/Vertex.o"
	@echo "... core/data/notstable/graph/Vertex.i"
	@echo "... core/data/notstable/graph/Vertex.s"
	@echo "... core/data/ocr/OCR.o"
	@echo "... core/data/ocr/OCR.i"
	@echo "... core/data/ocr/OCR.s"
	@echo "... core/data/typeF/TypeTraitsF.o"
	@echo "... core/data/typeF/TypeTraitsF.i"
	@echo "... core/data/typeF/TypeTraitsF.s"
	@echo "... core/data/utility/BasicUtility.o"
	@echo "... core/data/utility/BasicUtility.i"
	@echo "... core/data/utility/BasicUtility.s"
	@echo "... core/data/utility/CollectorExecutionInformation.o"
	@echo "... core/data/utility/CollectorExecutionInformation.i"
	@echo "... core/data/utility/CollectorExecutionInformation.s"
	@echo "... core/data/utility/Exception.o"
	@echo "... core/data/utility/Exception.i"
	@echo "... core/data/utility/Exception.s"
	@echo "... core/data/utility/XML.o"
	@echo "... core/data/utility/XML.i"
	@echo "... core/data/utility/XML.s"
	@echo "... core/data/video/Video.o"
	@echo "... core/data/video/Video.i"
	@echo "... core/data/video/Video.s"
	@echo "... core/dependency/MTRand.o"
	@echo "... core/dependency/MTRand.i"
	@echo "... core/dependency/MTRand.s"
	@echo "... core/dependency/fparser.o"
	@echo "... core/dependency/fparser.i"
	@echo "... core/dependency/fparser.s"
	@echo "... core/dependency/jpgd.o"
	@echo "... core/dependency/jpgd.i"
	@echo "... core/dependency/jpgd.s"
	@echo "... core/dependency/jpge.o"
	@echo "... core/dependency/jpge.i"
	@echo "... core/dependency/jpge.s"
	@echo "... core/dependency/lodepng.o"
	@echo "... core/dependency/lodepng.i"
	@echo "... core/dependency/lodepng.s"
	@echo "... core/dependency/pugixml.o"
	@echo "... core/dependency/pugixml.i"
	@echo "... core/dependency/pugixml.s"
	@echo "... core/dependency/tinythread.o"
	@echo "... core/dependency/tinythread.i"
	@echo "... core/dependency/tinythread.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... population_sacha/Calculate_percentage_of_a_color_on_contours.o"
	@echo "... population_sacha/Calculate_percentage_of_a_color_on_contours.i"
	@echo "... population_sacha/Calculate_percentage_of_a_color_on_contours.s"
	@echo "... population_sacha/Choose_input_folder.o"
	@echo "... population_sacha/Choose_input_folder.i"
	@echo "... population_sacha/Choose_input_folder.s"
	@echo "... population_sacha/Close_regions.o"
	@echo "... population_sacha/Close_regions.i"
	@echo "... population_sacha/Close_regions.s"
	@echo "... population_sacha/Copy_original_image.o"
	@echo "... population_sacha/Copy_original_image.i"
	@echo "... population_sacha/Copy_original_image.s"
	@echo "... population_sacha/Create_dot_finished_file.o"
	@echo "... population_sacha/Create_dot_finished_file.i"
	@echo "... population_sacha/Create_dot_finished_file.s"
	@echo "... population_sacha/Create_results_folder.o"
	@echo "... population_sacha/Create_results_folder.i"
	@echo "... population_sacha/Create_results_folder.s"
	@echo "... population_sacha/Discriminate_capillaries_from_IVS.o"
	@echo "... population_sacha/Discriminate_capillaries_from_IVS.i"
	@echo "... population_sacha/Discriminate_capillaries_from_IVS.s"
	@echo "... population_sacha/Estimate_villi_density.o"
	@echo "... population_sacha/Estimate_villi_density.i"
	@echo "... population_sacha/Estimate_villi_density.s"
	@echo "... population_sacha/Extract_contours.o"
	@echo "... population_sacha/Extract_contours.i"
	@echo "... population_sacha/Extract_contours.s"
	@echo "... population_sacha/Find_thresholds_for_a_matrix.o"
	@echo "... population_sacha/Find_thresholds_for_a_matrix.i"
	@echo "... population_sacha/Find_thresholds_for_a_matrix.s"
	@echo "... population_sacha/Initial_segmentation.o"
	@echo "... population_sacha/Initial_segmentation.i"
	@echo "... population_sacha/Initial_segmentation.s"
	@echo "... population_sacha/Load_placenta_picture.o"
	@echo "... population_sacha/Load_placenta_picture.i"
	@echo "... population_sacha/Load_placenta_picture.s"
	@echo "... population_sacha/Log_steps.o"
	@echo "... population_sacha/Log_steps.i"
	@echo "... population_sacha/Log_steps.s"
	@echo "... population_sacha/Open_regions.o"
	@echo "... population_sacha/Open_regions.i"
	@echo "... population_sacha/Open_regions.s"
	@echo "... population_sacha/Output_statistics.o"
	@echo "... population_sacha/Output_statistics.i"
	@echo "... population_sacha/Output_statistics.s"
	@echo "... population_sacha/Read_next_image.o"
	@echo "... population_sacha/Read_next_image.i"
	@echo "... population_sacha/Read_next_image.s"
	@echo "... population_sacha/Remove_IVS_and_villous_regions_by_area.o"
	@echo "... population_sacha/Remove_IVS_and_villous_regions_by_area.i"
	@echo "... population_sacha/Remove_IVS_and_villous_regions_by_area.s"
	@echo "... population_sacha/Remove_IVS_inside_villi.o"
	@echo "... population_sacha/Remove_IVS_inside_villi.i"
	@echo "... population_sacha/Remove_IVS_inside_villi.s"
	@echo "... population_sacha/Small_functions.o"
	@echo "... population_sacha/Small_functions.i"
	@echo "... population_sacha/Small_functions.s"
	@echo "... population_sacha/Smooth_out_the_contours.o"
	@echo "... population_sacha/Smooth_out_the_contours.i"
	@echo "... population_sacha/Smooth_out_the_contours.s"
	@echo "... population_sacha/Statistics_placenta.o"
	@echo "... population_sacha/Statistics_placenta.i"
	@echo "... population_sacha/Statistics_placenta.s"
	@echo "... population_sacha/class_RLE_Image.o"
	@echo "... population_sacha/class_RLE_Image.i"
	@echo "... population_sacha/class_RLE_Image.s"
	@echo "... population_sacha/class_Run.o"
	@echo "... population_sacha/class_Run.i"
	@echo "... population_sacha/class_Run.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

